---
title: 'RMarkdown'
author: "Emma Li"
output:
  slidy_presentation:
    duration: 45
    fig_height: 3
    fig_width: 6
  beamer_presentation:
    colortheme: dolphin
---

## Review
1. GettingStarted
2. BasicData: variables, statistics, tables, 
3. Visualization: ggplots
4. ChainLadder: triangles, more plots
5. OtherReserving: triangles, more plots


## to create a project, organize the functions
1. Data import and cleaning: read.csv()
2. Data summary: summary()
3. Visualization: ggplot()
4. Chainladder:
5. Compare with other reserving: 

## Option A
1. Calculate the new objects, such as statistics, new variables, tables, graphs and etc.
2. Copy and paste in PowerPoint. 

## Option B
1. Create a pipeline and R Markdown
2. Output it to PDF, Word or HTML


## Introduction
RMarkdown is a format that combines R code chunks with markdown syntax (a plain text format) 

in a rmd file, there are 3 components

* format (control the first page and the output format PDF, HTML, Word)
* r chunk: tables, plots, regressions
* plain text format markdown symtax: headers(different sizes), dashes, equations, imagess, lists, jpg


## Different

Since R Markdown has more advantages then R script, it has to be different.

1. Only can be run in RStudio IDE	
2. rmd file
3. R codes should be written in chunks 
4. You can run R codes, Knit HTML, Knit PDF or Knit Word
5. take advatange of Templates


## Installation 
1. download from https://www.rstudio.com/products/rstudio/download/.
2. jpg
   > install.packages(“rmarkdown”)
   > library(“rmarkdown”)

3. open a tempalte rmd. (creating HTML output, for example) 
4. run R codes, Knit HTML, Knit PDF or Knit Word

## More Details: 1. Format
---
title: 'RMarkdown'
author: "Emma Li"
output: html_document
---

## More Details: 2. R chunk:
'''
exactly the same for tables, plots, regressions
'''

## More Details: 3. plain text format
headers(different sizes), 
dashes, 
equations, 
imagess, 
lists, 
jpg
echo

## Example: reorganize the syntax I show you
jpg. (rmd frmo read.csv to reserving)


## Example: output
jpg.

## Q & A
