# Dependencies
markdown:         Kramdown

# Permalinks
permalink:        pretty

# Setup
title:            raw_clrs
tagline:          'CLRS'
description:      'Information about the R Workshop at the CLRS'
url:              http://pirategrunt.github.io/raw_clrs/
baseurl:          /raw_clrs

author:
  name:           'Brian A. Fannin'
  url:            https://PirateGrunt.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/PirateGrunt/raw_clrs
